/// <reference types="@arcgis/map-components/types/react" />

import "@makkah-municipality-gis/ui/mantine-styles";

import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { serializeRuntimeConfig } from "@/lib/runtimeConfig.server";

import AppProviders from "./theme/AppProviders";
import { themeBootstrapScript } from "./theme/themeScript";

// Read the ArcGIS tokens at request time (not build time) so one self-hosted build
// can be pointed at any environment via its env file. `force-dynamic` keeps this
// route out of the static prerender, so `process.env` reflects the running server.
export const dynamic = "force-dynamic";

const IBMSans = IBM_Plex_Sans_Arabic({
  variable: "--font-ibm-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // dir must be a real DOM attribute, not just CSS `direction`: Mantine mirrors its
  // direction-sensitive icons (e.g. calendar month chevrons) via [dir="rtl"] selectors.
  // suppressHydrationWarning: the bootstrap script stamps `data-theme` /
  // `data-mantine-color-scheme` on <html> before React hydrates.
  return (
    <html lang="ar" dir="rtl" className={`${IBMSans.variable}`} suppressHydrationWarning>
      <body>
        {/* Sets `data-theme` from localStorage (falling back to the OS preference)
            before hydration, so dark-mode users never see a light-mode flash.
            `themeBootstrapScript` lives in a plain (non "use client") module so it
            can be called here, from a server component. */}
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: trusted, no user input — see themeScript.ts
          dangerouslySetInnerHTML={{ __html: themeBootstrapScript() }}
        />
        {/* Hydrate runtime ArcGIS tokens before the app bundle loads. Server-built,
            trusted, and `<`-escaped — see runtimeConfig.server.ts. */}
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: trusted server-built config bootstrap
          dangerouslySetInnerHTML={{ __html: serializeRuntimeConfig() }}
        />
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
